### ISSUE TITLE
Php notification error whene editing notification settings in the ucp

### ISSUE THREAD

**Issue by toxyy** [blitze/phpBB-ext-sitemaker#48] opened 2019-03-30 11:18 UTC
Using the dev branch, I get this when trying to edit notification settings in the ucp (url forums/ucp.php?i=ucp_notifications&mode=notification_options):

```
[Sat Mar 30 07:03:40.752098 2019] [php7:error] [pid 20476:tid 1904] [client 97.81.89.219:62426] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to phpbb\\notification\\type\\base::__construct() must implement interface phpbb\\db\\driver\\driver_interface, instance of phpbb\\user_loader given in D:\\xampp\\htdocs\\forums\\phpbb\\notification\\type\\base.php:87\nStack trace:\n#0 [internal function]: phpbb\\notification\\type\\base->__construct(Object(phpbb\\user_loader), Object(phpbb\\db\\driver\\factory), Object(phpbb\\cache\\driver\\file), Object(phpbb\\user), Object(phpbb\\auth\\auth), Object(phpbb\\config\\db), './', 'php', 'phpbb_notificat...', 'phpbb_notificat...', 'phpbb_user_noti...')\n#1 D:\\xampp\\htdocs\\forums\\vendor\\symfony\\dependency-injection\\ContainerBuilder.php(925): ReflectionClass->newInstanceArgs(Array)\n#2 D:\\xampp\\htdocs\\forums\\vendor\\symfony\\dependency-injection\\ContainerBuilder.php(467): Symfony\\Component\\DependencyInjection\\ContainerBuilder->createService(Object(Symfony\\Component\\DependencyInjection\\Definition), Object(SplObjectStorage), 'forumpromotion....')\n#3 D:\\xampp\\htdocs\\forums\\phpbb\\di\\service_collection.php(72): Symf in D:\\xampp\\htdocs\\forums\\phpbb\\notification\\type\\base.php on line 87
97.81.89.219 - - [30/Mar/2019:07:03:39 -0400] "GET /forums/ucp.php?i=ucp_notifications&mode=notification_options HTTP/1.1" 200 1152
```

Full error:

```

Fatal error: Uncaught TypeError: Argument 1 passed to phpbb\notification\type\base::__construct() must implement interface phpbb\db\driver\driver_interface, instance of phpbb\user_loader given in D:\xampp\htdocs\forums\phpbb\notification\type\base.php:87 Stack trace: #0 [internal function]: phpbb\notification\type\base->__construct(Object(phpbb\user_loader), Object(phpbb\db\driver\factory), Object(phpbb\cache\driver\file), Object(phpbb\user), Object(phpbb\auth\auth), Object(phpbb\config\db), './', 'php', 'phpbb_notificat...', 'phpbb_notificat...', 'phpbb_user_noti...') #1 D:\xampp\htdocs\forums\vendor\symfony\dependency-injection\ContainerBuilder.php(925): ReflectionClass->newInstanceArgs(Array) #2 D:\xampp\htdocs\forums\vendor\symfony\dependency-injection\ContainerBuilder.php(467): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Object(SplObjectStorage), 'forumpromotion....') #3 D:\xampp\htdocs\forums\phpbb\di\service_collection.php(72): Symf in D:\xampp\htdocs\forums\phpbb\notification\type\base.php on line 87
```

I use a page made by phpbb pages as a start page.  Disabling this extension makes the error go away.

**Comment by blitze** [comment] 2019-05-12 19:45
I am unable to reproduce this. By the way, this extension itself does not touch the notification system. Now, the sitemaker content extension does touch the notification system but I am also not able to reproduce there. So I will close this issue for now

**Closed by blitze** 2019-05-12 19:45 UTC
