### ISSUE TITLE
Lang issue

### ISSUE THREAD

**Issue by Sippan-66** [blitze/phpBB-ext-sitemaker#15] opened 2016-03-14 10:01 UTC
Can't translate USER hard coded :-)

![2016-03-14_110041](https://cloud.githubusercontent.com/assets/17803396/13741004/12216bde-e9d4-11e5-9361-d228d5fc2d0e.png)

**Comment by blitze** [comment] 2016-03-14 13:59
Is this the members block? What settings (Recent members, Recent Bots, etc)?

**Comment by Sippan-66** [comment] 2016-03-14 14:03
its Featured members and  Recent Members

**Comment by blitze** [comment] 2016-03-15 03:34
Not sure this is happening but it only happens in phpBB 3.2.x. Assigning a value to a language string in php is overwritten in the template. E.g in php, 'L_USER' => $user->lang('SOME_LANG_KEY') does not work because in the template, {L_USER} is translated as 'User', if that makes sense. Either way, the issue is fixed now.

**Closed by blitze** 2016-03-15 03:34 UTC
